/* 
 * File:   mcal_internal_interrupts.h
 * Author: Mansour
 *
 * Created on December 1, 2023, 2:21 PM
 */

#ifndef MCAL_INTERNAL_INTERRUPTS_H
#define	MCAL_INTERNAL_INTERRUPTS_H

/*   section: Includes  */
#include "mcal_interrupt_cfg.h"

/*   section: Macros  */


/*   section: Macro Functions declarations */

/*  ADC INTERRUPT CONFIGURATIONS MACRO FUNCTIONS */
#if ADC_INTERRUPT_CFG_ENABLE == 1

#define ADC_INTERRUPT_ENABLE() (PIE1bits.ADIE = 1 )
#define ADC_INTERRUPT_DISABLE() (PIE1bits.ADIE = 0 )
#define ADC_INTERRUPT_CLEAR_FLAG() (PIR1bits.ADIF =0 )


#ifdef INTERRUPT_PRIORITY_LEVELS_FEATURE_ENABLE
#define ADC_INTERRUPT_HIGH_PRIORITY_ENABLE() (IPR1bits.ADIP = 1 )
#define ADC_INTERRUPT_LOW_PRIORITY_ENABLE() (IPR1bits.ADIP = 0 )
#endif

#endif 

/*  TIMER0 INTERRUPT CONFIGURATIONS MACRO FUNCTIONS */
#if TMR0_INTERRUPT_CFG_ENABLE == 1

#define TMR0_INTERRUPT_ENABLE() (INTCONbits.TMR0IE = 1 )
#define TMR0_INTERRUPT_DISABLE() (INTCONbits.TMR0IE = 0 )
#define TMR0_INTERRUPT_CLEAR_FLAG() (INTCONbits.TMR0IF = 0 )

#ifdef INTERRUPT_PRIORITY_LEVELS_FEATURE_ENABLE
#define TMR0_INTERRUPT_HIGH_PRIORITY_ENABLE() (INTCON2bits.TMR0IP = 1 )
#define TMR0_INTERRUPT_LOW_PRIORITY_ENABLE() (INTCON2bits.TMR0IP = 0 )
#endif

#endif

/*  TIMER1 INTERRUPT CONFIGURATIONS MACRO FUNCTIONS */
#if TMR1_INTERRUPT_CFG_ENABLE == 1

#define TMR1_INTERRUPT_ENABLE() (PIE1bits.TMR1IE = 1)
#define TMR1_INTERRUPT_DISABLE() (PIE1bits.TMR1IE = 0)
#define TMR1_INTERRUPT_CLEAR_FLAG() (PIR1bits.TMR1IF = 0)

#ifdef INTERRUPT_PRIORITY_LEVELS_FEATURE_ENABLE
#define TMR1_INTERRUPT_HIGH_PRIORITY_ENABLE() (IPR1bits.TMR1IP = 1)
#define TMR1_INTERRUPT_LOW_PRIORITY_ENABLE() (IPR1bits.TMR1IP = 0)
#endif

#endif

/*  TIMER2 INTERRUPT CONFIGURATIONS MACRO FUNCTIONS */
#if TMR2_INTERRUPT_CFG_ENABLE == 1

#define TMR2_INTERRUPT_ENABLE() (PIE1bits.TMR2IE = 1)
#define TMR2_INTERRUPT_DISABLE() (PIE1bits.TMR2IE = 0)
#define TMR2_INTERRUPT_CLEAR_FLAG() (PIR1bits.TMR2IF = 0)

#ifdef INTERRUPT_PRIORITY_LEVELS_FEATURE_ENABLE
#define TMR2_INTERRUPT_HIGH_PRIORITY_ENABLE() (IPR1bits.TMR2IP = 1)
#define TMR2_INTERRUPT_LOW_PRIORITY_ENABLE() (IPR1bits.TMR2IP = 0)
#endif

#endif

/*  TIMER3 INTERRUPT CONFIGURATIONS MACRO FUNCTIONS */
#if TMR3_INTERRUPT_CFG_ENABLE == 1

#define TMR3_INTERRUPT_ENABLE() (PIE2bits.TMR3IE = 1)
#define TMR3_INTERRUPT_DISABLE() (PIE2bits.TMR3IE = 0)
#define TMR3_INTERRUPT_CLEAR_FLAG() (PIR2bits.TMR3IF = 0)

#ifdef INTERRUPT_PRIORITY_LEVELS_FEATURE_ENABLE
#define TMR3_INTERRUPT_HIGH_PRIORITY_ENABLE() (IPR2bits.TMR3IP = 1)
#define TMR3_INTERRUPT_LOW_PRIORITY_ENABLE() (IPR2bits.TMR3IP = 0)
#endif

#endif

/*  CCP1 INTERRUPT CONFIGURATIONS MACRO FUNCTIONS */
#if CCP1_INTERRUPT_CFG_ENABLE == 1

#define CCP1_INTERRUPT_ENABLE() (PIE1bits.CCP1IE = 1)
#define CCP1_INTERRUPT_DISABLE() (PIE1bits.CCP1IE = 0)
#define CCP1_INTERRUPT_CLEAR_FLAG() (PIR1bits.CCP1IF = 0)

#ifdef INTERRUPT_PRIORITY_LEVELS_FEATURE_ENABLE
#define CCP1_INTERRUPT_HIGH_PRIORITY_ENABLE() (IPR1bits.CCP1IP = 1)
#define CCP1_INTERRUPT_LOW_PRIORITY_ENABLE() (IPR1bits.CCP1IP = 0)
#endif

#endif

/*  CCP2 INTERRUPT CONFIGURATIONS MACRO FUNCTIONS */
#if CCP2_INTERRUPT_CFG_ENABLE == 1

#define CCP2_INTERRUPT_ENABLE() (PIE2bits.CCP2IE = 1)
#define CCP2_INTERRUPT_DISABLE() (PIE2bits.CCP2IE = 0)
#define CCP2_INTERRUPT_CLEAR_FLAG() (PIR2bits.CCP2IF = 0)

#ifdef INTERRUPT_PRIORITY_LEVELS_FEATURE_ENABLE
#define CCP2_INTERRUPT_HIGH_PRIORITY_ENABLE() (IPR2bits.CCP2IP = 1)
#define CCP2_INTERRUPT_LOW_PRIORITY_ENABLE() (IPR2bits.CCP2IP = 0)
#endif

#endif

/*  USART TRANSMIT INTERRUPT CONFIGURATIONS MACRO FUNCTIONS */
#if USART_TRANSMIT_INTERRUPT_CFG_ENABLE == 1

#define USART_TRANSMIT_INTERRUPT_ENABLE() (PIE1bits.TXIE = 1)
#define USART_TRANSMIT_INTERRUPT_DISABLE() (PIE1bits.TXIE = 0)
// no flag clearing ( TXIF read only)

#ifdef INTERRUPT_PRIORITY_LEVELS_FEATURE_ENABLE
#define USART_TRANSMIT_INTERRUPT_HIGH_PRIORITY_ENABLE() (IPR1bits.TXIP = 1)
#define USART_TRANSMIT_INTERRUPT_LOW_PRIORITY_ENABLE() (IPR1bits.TXIP = 0)
#endif

#endif

/*  USART RECEIVE INTERRUPT CONFIGURATIONS MACRO FUNCTIONS */
#if USART_RECEIVE_INTERRUPT_CFG_ENABLE == 1

#define USART_RECEIVE_INTERRUPT_ENABLE() (PIE1bits.RCIE = 1)
#define USART_RECEIVE_INTERRUPT_DISABLE() (PIE1bits.RCIE = 0)
// no flag clearing ( RCIF read only)

#ifdef INTERRUPT_PRIORITY_LEVELS_FEATURE_ENABLE
#define USART_RECEIVE_INTERRUPT_HIGH_PRIORITY_ENABLE() (IPR1bits.RCIP = 1)
#define USART_RECEIVE_INTERRUPT_LOW_PRIORITY_ENABLE() (IPR1bits.RCIP = 0)
#endif

#endif

/*  SPI INTERRUPT CONFIGURATIONS MACRO FUNCTIONS */
#if SPI_INTERRUPT_CFG_ENABLE == 1

#define SPI_INTERRUPT_ENABLE()  (PIE1bits.SSPIE = 1)
#define SPI_INTERRUPT_DISABLE() (PIE1bits.SSPIE = 0)
#define SPI_INTERRUPT_CLEAR_FLAG() (PIR1bits.SSPIF = 0)

#ifdef INTERRUPT_PRIORITY_LEVELS_FEATURE_ENABLE
#define SPI_INTERRUPT_HIGH_PRIORITY_ENABLE() (IPR1bits.SSPIP = 1)
#define SPI_INTERRUPT_LOW_PRIORITY_ENABLE()  (IPR1bits.SSPIP = 0)
#endif

#endif

/*   section: Data Types declarations */


/*   section: Function declarations  */

#endif	/* MCAL_INTERNAL_INTERRUPTS_H */

