/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: Mansour
 *
 * Created on December 1, 2023, 3:54 PM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

#define INTERRUPT_FEATURE_ENABLE 1

#define INTERRUPT_PRIORITY_LEVELS_FEATURE_ENABLE

#define INTERRUPT_EXTERNAL_INTx_FEATURE_ENABLE
#define INTERRUPT_EXTERNAL_IOC_FEATURE_ENABLE

#define ADC_INTERRUPT_CFG_ENABLE INTERRUPT_FEATURE_ENABLE

#define TMR0_INTERRUPT_CFG_ENABLE INTERRUPT_FEATURE_ENABLE
#define TMR1_INTERRUPT_CFG_ENABLE INTERRUPT_FEATURE_ENABLE
#define TMR2_INTERRUPT_CFG_ENABLE INTERRUPT_FEATURE_ENABLE
#define TMR3_INTERRUPT_CFG_ENABLE INTERRUPT_FEATURE_ENABLE

#define CCP1_INTERRUPT_CFG_ENABLE INTERRUPT_FEATURE_ENABLE
#define CCP2_INTERRUPT_CFG_ENABLE INTERRUPT_FEATURE_ENABLE

#define USART_TRANSMIT_INTERRUPT_CFG_ENABLE INTERRUPT_FEATURE_ENABLE
#define USART_RECEIVE_INTERRUPT_CFG_ENABLE INTERRUPT_FEATURE_ENABLE

//#define SPI_INTERRUPT_CFG_ENABLE INTERRUPT_FEATURE_ENABLE



#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

